version: "3"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - nginx
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel     

    # Use MariaDB instead of MySQL
    mariadb:
        image: mariadb:latest  # Use official MariaDB image
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
            MYSQL_USER: ${DB_USERNAME:-username}
        volumes:
            - ./.docker/mariadb/dbdata:/var/lib/mariadb  # Persistent storage for database
        ports:
            - "3306:3306"  # Default MariaDB port
        networks:
            - laravel

    # PHPMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        platform: linux/x86_64
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
        networks:
            - laravel
    
    # node 
    node:
        image: node:latest
        volumes:
            - ./:/var/www
        working_dir: /var/www
        ports:
            - "3000:3000"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
